config/routes.rb
TrlnArgon::Engine.routes.draw do
  scope module: 'trln_argon' do
    resources :healthchecks, path: '/health', action: :index
  end

  get 'catalog/suggest/:category', to: 'catalog#suggest'
  get 'trln/suggest/:category', to: 'trln#suggest'
  get 'trln/advanced', to: 'trln#advanced_search'
  get 'catalog_count_only', to: 'catalog#count_only', as: 'catalog_count_only'
  get 'trln_count_only', to: 'trln#count_only', as: 'trln_count_only'
  get 'hathitrust/:oclc_numbers', to: 'hathitrust#show', as: 'hathitrust'
  get 'internet_archive/:internet_archive_ids', to: 'internet_archive#show', as: 'internet_archive'

  # redirects for blacklight_advanced_search plugin former URLs
  get '/advanced', to: redirect('catalog/advanced')
  get '/advanced_trln', to: redirect('trln/advanced')

  get 'logs' => 'catalog#logs', as: 'logs'
end

app/views/advanced/index.html.erb
<% @page_title = "#{t('blacklight_advanced_search.form.title')} - #{application_name}" %>

<div class="<%= advanced_search_page_class %>" id="content" role="main">

    <h1 class="advanced page-header">
        <%= t('blacklight_advanced_search.form.title') %>
        <%= link_to t('blacklight_advanced_search.form.start_over'), advanced_search_url, :class =>"btn btn-default pull-right advanced-search-start-over" %>
    </h1>

    <div class="row">

        <div class="<%= advanced_search_form_class %>">
            <%= render 'advanced_search_form' %>
        </div>
        <div class="<%= advanced_search_help_class %>">
            <%= render "advanced_search_help" %>
        </div>

    </div>

</div>